[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "sphinx-all-contributors"
dynamic = [
  "readme",
  "version"
]
requires-python = '>=3.12'

[tool.mypy]
ignore_missing_imports = true
strict = true
warn_unreachable = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = ["error"]
log_cli_level = "info"
testpaths = [
  "tests"
]

[tool.ruff.lint]
extend-select = ["ALL"]
ignore = ["COM812", "D203", "D212", "ISC001"]
