[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[tool.mypy]
ignore_missing_imports = true
strict = true
warn_unreachable = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = ["error"]
log_cli_level = "info"
testpaths = [
  "tests"
]

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
extend-select = [
  "B", # flake8-bugbear
  "I", # isort
  "UP" # pyupgrade
]
