name: "Pull Request Labeler"
on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
          configuration-path: .github/labeler.yml
          dot: true
      - run: gh pr edit "${{ github.event.pull_request.number }}" --add-label "ignore-for-release" --repo "${{ github.repository }}"
        if: github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'github-actions[bot]' || github.event.pull_request.user.login == 'pre-commit-ci[bot]'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
